-- migration4.sql: Add sticky note support + more vocabulary words across articles
-- Run after migration3.sql

-- Additional vocabulary words across multiple articles
insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('stuck', 'stuhk', 'adjective', 'unable to move or make progress; feeling trapped in a situation', 'She felt stuck between who she was and who she wanted to be.', 'Old English stician, to pierce or remain fixed.', 'Not the same as lazy - stuck means you want to move but cannot find the direction.', array['trapped','paralyzed','blocked'], array['I have been stuck on this decision for weeks.'], (select id from articles where slug = 'feeling-stuck-going-nowhere'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('compound', 'kum-POWND', 'verb', 'to increase or grow by adding smaller things over time', 'Small decisions compound into a life you recognize.', 'From Latin compunare, to put together.', 'Not the same as accumulate; compounding implies each addition grows the next.', array['accumulate','build','snowball'], array['Good habits compound - one workout becomes a year of fitness.'], (select id from articles where slug = 'learning-to-make-smaller-decisions'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('cadence', 'KAY-dence', 'noun', 'the rhythm and flow of language or movement', 'Natural English comes from cadence - the music of small words spoken with conviction.', 'From Latin cadere, to fall.', 'Not the same as tempo - cadence includes the rise and fall, not just speed.', array['rhythm','flow','tempo'], array['Her cadence changed when she talked about the thing that mattered.'], (select id from articles where slug = 'how-to-sound-natural-in-english'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('obsession', 'uhb-SEH-shuhn', 'noun', 'a persistent thought or concern that dominates attention', 'Focus without obsession means caring deeply without losing yourself.', 'From Latin obsessio, a siege.', 'Not the same as passion - passion fuels you; obsession consumes you.', array['fixation','preoccupation','mania'], array['Passion is a compass; obsession is a cage.'], (select id from articles where slug = 'focus-without-obsession'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('confidence', 'KON-fih-dence', 'noun', 'a bet you keep placing on yourself, not proof of past success', 'Real confidence is not the memory of past success - it is a bet you keep placing.', 'From Latin confidere, to trust fully.', 'Not the same as certainty - confidence acts despite uncertainty.', array['self-trust','assurance','boldness'], array['Confidence without proof sounds impossible until you realize every first attempt is exactly that.'], (select id from articles where slug = 'confidence-without-proof'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('decision', 'sih-SIZH-uhn', 'noun', 'a choice between options, especially after thought or discussion', 'Big choices overwhelm; small ones compound into direction.', 'From Latin decidere, to cut off.', 'Not the same as a preference - a decision commits you to act.', array['choice','resolution','verdict'], array['Stop waiting for the perfect decision. Make one and adjust.'], (select id from articles where slug = 'how-to-make-a-big-decision'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('momentum', 'moh-MEN-tum', 'noun', 'the force that keeps something moving once it has started', 'Momentum is a spark, not a fuel. The real engine is smaller and stranger.', 'From Latin momen, movement.', 'Not the same as motivation - motivation starts things; momentum keeps them going.', array['impetus','inertia','drive'], array['Once you start, momentum does most of the work.'], (select id from articles where slug = 'how-people-actually-change'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('habit', 'HAB-it', 'noun', 'a settled tendency or practice, especially one that is hard to give up', 'Any routine that only works when life is calm is a hobby, not a habit.', 'From Latin habere, to have or hold. A habit is something you hold onto.', 'Not the same as routine - a habit runs on autopilot; a routine requires decision.', array['routine','practice','pattern'], array['The habit of reading before bed changed everything.'], (select id from articles where slug = 'habits-that-survive-bad-weeks'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('direction', 'dih-REK-shuhn', 'noun', 'a course along which someone or something moves; a purpose or aim', 'Everyone asks where you are headed. Fewer ask who you are becoming.', 'From Latin dirigere, to straighten or arrange.', 'Not the same as a goal - direction is the general heading; goals are the milestones.', array['course','aim','purpose'], array['I do not have a destination yet, but I have a direction.'], (select id from articles where slug = 'pressure-to-have-a-direction'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('change', 'chaynj', 'noun', 'the act of becoming different; a transformation or transition', 'The most important shifts in a life often happen before they are visible.', 'From Late Latin cambiare, to exchange.', 'Not the same as improvement - change is any difference; improvement is the direction you want.', array['shift','transition','transformation'], array['Change does not announce itself. It arrives quietly and you notice it after.'], (select id from articles where slug = 'why-change-sometimes-looks-like-nothing'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('apostrophe', 'uh-POS-truh-fee', 'noun', 'a punctuation mark used to indicate possession or contraction', 'The most feared punctuation mark is actually two quiet jobs wearing one hat.', 'From Greek apostrophos, a turning away. The mark turns letters away.', 'Its vs it is. Your vs you are. The apostrophe always means something is missing.', array['comma','quotation marks','ellipsis'], array['The apostrophe is not decoration - it is information.'], (select id from articles where slug = 'grammar-in-context-the-apostrophe'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();

insert into vocabulary_words (word, pronunciation, part_of_speech, plain_meaning, usage_example, etymology, common_mistakes, related_words, conversation_examples, source_article_id)
values ('attention', 'uh-TEN-shuhn', 'noun', 'the concentration of the mind on something; notice or noticeability', 'The speed of modern attention has changed what it means to be worth reading.', 'From Latin attendere, to stretch toward.', 'Not the same as focus - attention is the raw material; focus is what you do with it.', array['focus','concentration','awareness'], array['Attention is the most valuable currency on the internet.'], (select id from articles where slug = 'the-speed-of-modern-attention'))
on conflict (word) do update set pronunciation = excluded.pronunciation, common_mistakes = excluded.common_mistakes, source_article_id = excluded.source_article_id, updated_at = now();
