/**
 * THE HUMAN EDIT - Sample article content (section 48 seed)
 *
 * 22 sample articles across all six corners, one reading path,
 * vocabulary entries. Written to demonstrate every major component:
 * essays, stories, guides, lessons, vocabulary features, reflections.
 * All articles are flagged isSample=true and purged before production.
 */

export interface SeedArticle {
  slug: string;
  title: string;
  dek: string;
  corner: string;
  topics: string[];
  contentType:
    | "essay" | "story" | "guide" | "opinion" | "interview" | "lesson"
    | "vocabulary" | "reflection" | "explainer";
  readingDepth: "quick" | "standard" | "deep";
  body: string[]; // paragraphs; "## " prefix = heading
  authorName: string;
}

export const AUTHORS: Record<string, string> = {
  amara: "Amara Sen",
  dev: "Dev Rao",
  june: "June Park",
  marcus: "Marcus Hale",
  nila: "Nila Anand",
  thea: "Thea Lindqvist",
};

export const ARTICLES: SeedArticle[] = [
  {
    slug: "feeling-stuck-going-nowhere",
    title: "Why Feeling Stuck Doesn't Mean You're Going Nowhere",
    dek: "A reflection on the strange gap between wanting change and knowing what to change.",
    corner: "human",
    topics: ["starting-over", "direction", "identity"],
    contentType: "reflection",
    readingDepth: "standard",
    authorName: AUTHORS.amara,
    body: [
      "There is a particular kind of tiredness that comes not from doing too much, but from wanting something you cannot name. You wake up, you go through the motions, and somewhere between the second cup of tea and the evening, a quiet question arrives: is this it?",
      "We tend to treat feeling stuck as a malfunction. Something to fix quickly, like a leaky tap. But most of the people I've talked to about this - and I've talked to many - describe something closer to a threshold. A waiting room between two versions of a life.",
      "## The gap is not emptiness",
      "The stuck feeling is usually described as a gap: between who you are and who you want to be, between the effort you make and the results you see. But a gap is not an emptiness. It is a distance. And distances, unlike holes, can be crossed.",
      "The problem is that we measure the distance with the wrong instruments. We look at other people's highlight reels and conclude we have not moved at all. We compare our internal weather to everyone else's visible architecture.",
      "## Small decisions, long horizons",
      "Here is what I have noticed about periods that felt stuck in hindsight: they were often the moments just before something shifted. Not because of one dramatic decision, but because of a hundred small ones - saying yes to a coffee with someone, reading one book that cracked a window open, admitting out loud, once, that the current life did not fit.",
      "When you feel stuck, the instinct is to look for one big move. Quit the job. Leave the city. End the relationship. Sometimes those are right. But more often, movement begins smaller: one honest conversation, one new route home, one hour of a Tuesday evening claimed for something that is only yours.",
      "## What to do with the waiting",
      "If you are in the waiting room, you can still choose what to bring into it. You can wait bitterly, or you can wait like a gardener - doing unglamorous work underground, trusting that roots count as progress even when nothing shows above the surface.",
      "Feeling stuck is not proof that your life has stopped. Sometimes it is just the feeling of a life rearranging itself faster than you can narrate. Be patient with your draft. You are still being written.",
    ],
  },
  {
    slug: "pressure-to-have-a-direction",
    title: "The Pressure to Have a Direction",
    dek: "Everyone asks what you do and where you're headed. Fewer ask who you're becoming.",
    corner: "human",
    topics: ["direction", "ambition", "adulthood"],
    contentType: "essay",
    readingDepth: "standard",
    authorName: AUTHORS.marcus,
    body: [
      "Somewhere in our collective imagination, a good life became a straight line. School, then training, then work, then more work, each stop explained in one tidy sentence at parties. We inherited a question - what do you do? - and quietly agreed to answer it with a direction.",
      "But a direction is a strange thing to demand of a person. A direction belongs to arrows and trains. Humans, as far as I can tell, are more like weather systems. We move, but we also form, dissolve, and reform.",
      "## The five-year question",
      "Interviewers ask it. Relatives ask it at dinners. Where do you see yourself in five years? It is a harmless question that has quietly terrorized generations of people who were doing the best thing available to them: paying attention to the present.",
      "I have nothing against plans. I am against the idea that a person without a plan is a person without value - or worse, without a future. Some of the most interesting lives I know were built by people who could only ever see two moves ahead, like climbing in fog.",
      "## Direction as permission",
      "Here is a gentler reframe. Direction does not have to be a destination you can name. It can be a quality of attention. You can be headed toward honesty. Toward work that absorbs you. Toward people who make you feel awake. None of those fit on a business card, and all of them will outlast most job titles.",
      "The pressure to have a direction is real, and I won't pretend otherwise. But you can feel it and still refuse its terms. A life is not a resignation letter. You are allowed to be in progress.",
    ],
  },
  {
    slug: "why-change-sometimes-looks-like-nothing",
    title: "Why Change Sometimes Looks Like Nothing",
    dek: "The most important shifts in a life often happen before they are visible.",
    corner: "human",
    topics: ["change", "starting-over", "personal-growth"],
    contentType: "reflection",
    readingDepth: "quick",
    authorName: AUTHORS.nila,
    body: [
      "For three months after I left the job that was quietly flattening me, I looked, to any outside observer, exactly the same. Same flat. Same city. Same slightly-too-long hair. Nothing had changed, and yet everything had - because I had stopped saying yes to things that hollowed me out.",
      "Change is a bad performer. It rarely announces itself. It works backstage for months, adjusting lighting and re-learning lines, and then one morning you notice you no longer dread a thing you used to dread.",
      "## The invisible curriculum",
      "We are taught to measure change in visible units: new job, new city, new body, new relationship status. But ask anyone when their life actually turned, and they will usually name something smaller. A sentence someone said. A book read at exactly the wrong time, which turned out to be the right one. A morning they woke up and simply did not return a call.",
      "If you are in a season where nothing seems to be happening, consider that the happening may be underground. Roots are famously unphotogenic. Nobody posts them.",
      "## Keep going",
      "Keep tending the thing no one can see yet. The visible will catch up. It always does - that is the entire trick of gardening, and of lives.",
    ],
  },
  {
    slug: "learning-to-make-smaller-decisions",
    title: "Learning to Make Smaller Decisions",
    dek: "Big choices overwhelm. Small ones compound. A practical case for lowering the stakes.",
    corner: "human",
    topics: ["decisions", "direction", "everyday-problems"],
    contentType: "essay",
    readingDepth: "standard",
    authorName: AUTHORS.june,
    body: [
      "I used to think the way out of an overwhelming life was one enormous, cinematic decision. Then I spent a year watching people actually change, and what I saw were kitchens, not earthquakes. A different route to work. A Saturday morning class. A single honest sentence at a family dinner.",
      "Big decisions are seductive because they promise a clean break from complexity. But they carry a tax: they require courage, timing, certainty - three things rarely in stock at the same time. So we wait to feel ready, and the big decision never comes, and we call this being stuck.",
      "## The two-week rule",
      "Here is a practice that helped me: shrink every decision until it fits inside two weeks. Not what career should I pursue - what is one thing I can try for two weeks? Not should I leave this city - where can I go for two weekends? Small decisions are cheap to make, cheap to undo, and strangely good at revealing what you actually want.",
      "Because here is the secret: you cannot think your way to the big answer. You can only act your way toward better questions. And small decisions generate an extraordinary amount of data.",
      "## Compound interest of the soul",
      "Small decisions also stack. One two-week experiment ends, another begins, and eighteen months later you are someone with a strange new competence, a new friend, a different relationship to mornings. You never once had to be brave. You only had to be slightly curious, repeatedly.",
      "Make the decision small enough to make today. That is the whole method.",
    ],
  },
  {
    slug: "building-a-life-you-recognize",
    title: "Building a Life You Actually Recognize",
    dek: "On slowly returning to yourself after years of performing someone else's idea of you.",
    corner: "human",
    topics: ["identity", "belonging", "starting-over"],
    contentType: "essay",
    readingDepth: "deep",
    authorName: AUTHORS.amara,
    body: [
      "There is a particular loneliness in living a life that looks correct from the outside and feels like someone else's coat from the inside. Everything checks out. The job makes sense. The apartment makes sense. And yet some nights you catch yourself in the mirror like a stranger leafing through your wallet.",
      "This essay is about the long, unremarkable process of coming back to a life you recognize. Not finding yourself - that phrase promises too much, as if the self were a set of keys lost behind a couch - but recognizing yourself, the way you recognize a song from three notes.",
      "## The borrowed life",
      "Most of us build our early lives from borrowed materials. Borrowed ambitions from parents, borrowed opinions from feeds, borrowed definitions of success from people we will never meet. The borrowed life is not a failure; it is a starter kit. The trouble starts only when you never swap the borrowed parts for your own.",
      "The swap usually begins with a flinch. A small, sharp moment where you realize you don't actually like this - the field, the city, the performance of it - and you have been saying you do for years. The flinch is not a crisis. It is an invitation.",
      "## What recognition feels like",
      "How do you know a life is yours? For me, the signs have been embarrassingly small. Feeling rested in a room whose mess is mine. Laughing in my actual laugh. Being bored without being anxious - boredom, it turns out, is only tolerable in a life you chose. Recognition rarely arrives as thunder. It arrives as a Tuesday that doesn't feel like a costume.",
      "## The slow rebuild",
      "The rebuild is slow, and it is made of restorations more than renovations. You put back things you abandoned at seventeen - the sketching, the drums, the long aimless walks - and discover they were never hobbies. They were load-bearing.",
      "You also subtract. You leave rooms where you must perform. You say the honest boring thing. You keep fewer people closer. A recognizable life is not a busier one; it is usually a smaller one, like a house you've finally stopped expanding.",
      "If you are mid-rebuild, be gentle. You are not behind. The self is not found but re-assembled, and re-assembly is quiet work, done mostly in kitchens and on walks, one honest hour at a time.",
    ],
  },
  {
    slug: "habits-that-survive-bad-weeks",
    title: "Habits That Survive Bad Weeks",
    dek: "Any routine that only works when life is calm is a hobby, not a habit.",
    corner: "growth",
    topics: ["habits", "discipline", "personal-growth"],
    contentType: "guide",
    readingDepth: "standard",
    authorName: AUTHORS.dev,
    body: [
      "Most habit advice is written for good weeks. It assumes you are a person with a predictable morning, a stable mood, and a life that cooperates. Then a bad week arrives - a deadline collapses, a cold circulates, a family thing flares up - and the beautiful routine turns out to be porcelain.",
      "This is a guide to building habits that bend. Not bigger habits. Rubberier ones.",
      "## Step one: define the floor",
      "For every habit you care about, define a floor - the smallest version that still counts. If you write, the floor might be one sentence. If you run, it is putting on shoes and walking around the block. The floor feels insultingly small on good days. That is the point. The floor is not for good days.",
      "A habit with a floor can survive a fever, a funeral, and a Monday. You never break the chain, because the chain is now made of rope, not glass.",
      "## Step two: attach, don't schedule",
      "Schedules break under pressure; attachments survive. Instead of writing at 7 a.m., write after your first coffee, whenever that happens. The anchor should be something that occurs daily even in chaos - you will always eat, always arrive home, always put your phone down at some point.",
      "## Step three: plan the bad week now",
      "Write your disaster protocol while calm: when life falls apart, I will do the floor version only, and I will not feel guilty about it. This sounds trivial. It is not. Most people quit habits not from lack of will but from the shame of a missed day metastasizing into a missed month.",
      "A missed day is data. A shame spiral is just weather.",
      "## What survives",
      "I have kept three habits through five genuinely bad years this way. All three have floors low enough to embarrass me. All three are, at this point, unbreakable - because they have already survived everything I could throw at them.",
    ],
  },
  {
    slug: "focus-without-obsession",
    title: "Learning to Focus Without Becoming Obsessed",
    dek: "Deep work shouldn't eat your life. A practical guide to attention with edges.",
    corner: "growth",
    topics: ["focus", "discipline", "learning"],
    contentType: "guide",
    readingDepth: "standard",
    authorName: AUTHORS.june,
    body: [
      "There is a version of focus that our culture sells hard: the monk mode, the 5 a.m. grind, the elimination of every pleasure until the goal is achieved. It works, briefly. Then it eats you. The question worth asking is not how to focus harder, but how to focus in a way that leaves your life intact.",
      "## Attention has edges",
      "Focused attention is a boundary, not a fire. The healthiest deep workers I know treat focus like a reserved table: it exists at certain hours, and outside those hours it does not follow them around. When they close the laptop, focus is done for the day. It does not sit at dinner whispering about tomorrow.",
      "Obsession has no closing time. It leaks into meals and friendships and the shower. If your goal takes up all your inner screen space - if you cannot enjoy a film because you should be working - that is not focus. That is a possession.",
      "## Three practical edges",
      "One: pick a finish line for the day. A single sentence describing what done looks like, written in the morning. When you cross it, stop - even at 2 p.m., even if you feel like a machine. Stopping while you still have fuel is how you get fuel tomorrow.",
      "Two: keep one arena deliberately untouched by ambition. A friend who never hears about the project. A walk that is never a podcast. This is not slacking; this is ballast.",
      "Three: measure weeks, not days. Obsessives measure days, so every evening is a verdict. Focused people measure weeks, which absorb bad days without drama.",
      "## The tell",
      "Here is the simple test: when you take a day off, does the thing you're working on feel like a home you'll return to, or a debt that followed you to the beach? Build the kind of focus that waits at home. It will still be there Monday, patient, with the kettle on.",
    ],
  },
  {
    slug: "confidence-without-proof",
    title: "Confidence Without Proof",
    dek: "Real confidence isn't the memory of past success. It's a bet you keep placing.",
    corner: "growth",
    topics: ["confidence", "personal-growth", "direction"],
    contentType: "essay",
    readingDepth: "standard",
    authorName: AUTHORS.marcus,
    body: [
      "We treat confidence like a trophy - something you earn once by winning, then display on the shelf of your personality forever. By this model, the only way to become confident is to succeed first. Which is terrible news for anyone starting anything.",
      "But watch people who begin things for a living - founders, artists, immigrants, people who switch careers at forty - and you'll notice something odd. Their confidence does not come from evidence. They act confident before the evidence exists, and the evidence follows.",
      "## Confidence as a bet, not a memory",
      "A better model: confidence is not a memory of past wins. It is a bet - the decision to act before certainty, and to keep acting. The confident person is not certain of success. They are certain they can handle the failure. That's the whole trick. The trophy model asks: will I win? The bet model asks: will I survive learning I was wrong?",
      "Almost always, yes. You have already survived every incorrect belief you have ever held.",
      "## Building the bet",
      "How do you make the bet practical? Small stakes, placed often. Send the email before the sentence is perfect. Say the opinion at the meeting. Wear the coat you think might be too much. Each tiny act of unproven action is a deposit into an account the trophy model cannot touch.",
      "And when the bet fails - it will, often - do the ritual that matters: name what happened without the extra layer of identity. Not I was rejected, therefore I am rejectable. Just: that one didn't land. Bets, not verdicts.",
      "## Quiet confidence",
      "The loudest confidence is usually anxiety in a suit. The real thing is quieter. It is the person asking the naive question in the meeting because they'd rather learn than look learned. It is doing the thing while still feeling the wobble. Confidence, it turns out, is not the absence of the wobble. It is the decision that the wobble doesn't get a vote.",
    ],
  },
  {
    slug: "how-people-actually-change",
    title: "How People Actually Change",
    dek: "Motivation is a spark, not a fuel. The real engine is smaller and stranger.",
    corner: "growth",
    topics: ["change", "habits", "learning"],
    contentType: "explainer",
    readingDepth: "deep",
    authorName: AUTHORS.nila,
    body: [
      "Every January, gyms fill with people holding a spark. The spark is motivation - vivid, hot, honest - and by February it is mostly gone, because that is what sparks do. We are told this means the people were weak and the goal was wrong. Neither is true. We simply keep trying to power a house with a lighter.",
      "If you look closely at how people genuinely change - not in advertisements, but in real lives over real years - the mechanism is smaller, stranger, and much more reliable than motivation.",
      "## Mechanism one: the environment does the work",
      "The person who quits smoking most reliably is often the one who moves, changes jobs, or loses the friend group that smoked. Not because willpower improved, but because the cues disappeared. Behavior lives inside rooms; change the room and the behavior negotiates.",
      "You can engineer this deliberately. Want to read more? Put the book where the phone currently lives; put the phone where the book currently lives. This sounds like a joke. It is applied neuroscience. The phone lives where it lives because it is the easiest thing to touch.",
      "## Mechanism two: identity outvotes goals",
      "Goals are directions; identity is the engine. The person who says I'm trying to run more is fighting themselves daily. The person who says I'm a runner, kind of, on Tuesdays has already stopped negotiating. Each small run is no longer an achievement to be rewarded - it is just a Tuesday, a thing their kind of person does.",
      "This is why the smallest identity claim matters more than the largest goal. I'm someone who finishes sentences - said about writing - outperforms I'll write a novel, because the second is judged daily by a jury and the first is just quietly true.",
      "## Mechanism three: the two-day rule",
      "Never miss twice. One missed day is noise; two missed days is a new pattern forming. The two-day rule protects the streak without demanding perfection - it builds a habit of returning, which is the actual skill. Everyone falls off. The changers are just the people who treat falling off as a stumble, not a verdict on their character.",
      "## Mechanism four: make it observable",
      "Unobserved progress decays. The training log, the journal, the mark on the calendar - these are not motivational trinkets. They convert invisible change into visible change, which the brain, a disappointing accountant, refuses to credit without paperwork.",
      "## The engine",
      "So the house runs on this: environment first, identity second, return-ability third, records fourth. Sparks still matter - they start things. But morning after morning, what carries you is quieter: a room that cooperates, a sentence about who you are, the rule about never missing twice, and a page where the miles are written down.",
    ],
  },
  {
    slug: "words-that-dont-translate",
    title: "Words That Don't Translate",
    dek: "Some English words carry feelings your language may keep as whole sentences.",
    corner: "english",
    topics: ["words", "word-origins", "expressions"],
    contentType: "lesson",
    readingDepth: "standard",
    authorName: AUTHORS.thea,
    body: [
      "The best part of learning a language is not the grammar - it's the moment you meet a word that your own language never bothered to build. English is full of them: small verbal machines built for one precise feeling. Today we look at three.",
      "## 1. Serendipity",
      "Serendipity means finding something good while looking for something else. You went out for bread; you came home with a best friend. The word comes from a Persian fairy tale about the Three Princes of Serendip, who were always discovering things by accident - and, crucially, noticing what they'd found.",
      "Notice the difference: luck is what happens to you. Serendipity is what you notice happening to you. That second part is trainable. Keep your eyes soft when you're looking for something else.",
      "Word to notice: serendipity - and yes, this word has its own vocabulary card in the Library.",
      "## 2. Petrichor",
      "Petrichor is the smell of rain on dry earth. Before 1964, if you wanted to talk about this smell in English, you had to say the smell of rain on dry earth, like a farmer. Then two Australian scientists wrote a paper and invented a word from Greek: petra (stone) + ichor (the fluid that runs in gods' veins instead of blood).",
      "A language will happily carry a word for the blood of gods in wet stones for sixty years. English is like that.",
      "## 3. Sonder",
      "Sonder is a newer coinage - from the Dictionary of Obscure Sorrows - for the realization that every random passerby is living a life as vivid and complex as your own. The crowd on the train: every one of them has a mother, a worry about Thursday, a favorite spoon.",
      "Most languages need a paragraph for that. English, ever the collector of other people's precise feelings, now has a noun.",
      "## Your turn",
      "When you learn a word like this, don't just memorize it. Use it once this week, out loud, about your actual life. I found my flatmate's lost ring in the sofa - serendipity. Words enter memory through the mouth, not the eyes.",
    ],
  },
  {
    slug: "how-to-sound-natural-in-english",
    title: "How to Sound Natural in English",
    dek: "It's not about bigger words. It's about smaller, truer ones.",
    corner: "english",
    topics: ["speaking", "communication", "phrases"],
    contentType: "lesson",
    readingDepth: "standard",
    authorName: AUTHORS.thea,
    body: [
      "Learners often believe the road to sounding natural runs through impressive vocabulary. But listen to any good conversation between fluent speakers and count the impressive words: usually zero. Naturalness in English is not elevation. It is compression - saying true things in small words, quickly.",
      "## Principle one: verbs over nouns",
      "English loves verbs. Learners arriving from more formal academic traditions often say make a decision, provide assistance, and come to a conclusion. A fluent speaker says decide, help, and conclude. Same meaning, half the machinery. When you can compress, compress.",
      "## Principle two: the music matters more than the words",
      "Two sentences, both correct: I am not going to the party. Versus I'm not going to the party. The second sounds natural because English is a contracting language - fluent speakers shorten wherever gravity allows. I am, uncontracted, sounds like a lawyer announcing it.",
      "Stress the word that carries the news. I'm not going to the party (but my sister is). I'm not going to the party (I'll be at the other one). Meaning in spoken English lives in the stress like electricity in a wire.",
      "## Principle three: collect phrases, not words",
      "Nobody fluent says How are you? and assembles it from grammar. It's stored whole, like a piece of furniture. Natural speakers have thousands of these pre-assembled phrases - to be honest, at the end of the day, it's not that big a deal - and speak by retrieving furniture, not by building it from planks in real time.",
      "When you learn a word, learn its habitat. Not just rain, but heavy rain. Not just tired, but I'm a bit tired, honestly. The phrase is the unit of speech.",
      "## Principle four: small talk is a door, not a wall",
      "Small talk - the weather, the weekend, the commute - is not empty. It's a mutual handshake: we are safe, we are friendly, we may continue. Answer small questions with one detail and one return. How was your weekend? - Quiet, actually - I finally started that book. What about yours? That is the entire dance.",
      "## The honest secret",
      "Sounding natural is mostly sounding like you mean it. A learner who says, in imperfect English, I read this thing and it broke my heart a little sounds more fluent than someone deploying vocabulary like marble columns. Fluency is warmth at speed. Warmth first.",
    ],
  },
  {
    slug: "grammar-in-context-the-apostrophe",
    title: "Grammar in Context: The Apostrophe",
    dek: "The most feared punctuation mark is actually two quiet jobs wearing one hat.",
    corner: "english",
    topics: ["grammar-in-context", "writing", "words"],
    contentType: "lesson",
    readingDepth: "quick",
    authorName: AUTHORS.dev,
    body: [
      "The apostrophe has frightened more people out of writing than any other punctuation mark. It shouldn't. It has exactly two jobs, and both are older than the rules invented to confuse them.",
      "## Job one: standing in for missing letters",
      "Don't = do not. It's = it is. The apostrophe is a tiny hole where letters fell out. If you can expand the word back into two words and the sentence still works, the apostrophe belongs: She's gone - She is gone. Correct.",
      "## Job two: showing ownership",
      "Amara's coat. The town's only bakery. The apostrophe after an owner says this belongs to them. If the owner is plural and ends in s, the extra s is optional - the students' desks - and nobody at any party has ever cared which you chose.",
      "## The famous trap",
      "Its vs. it's. The trap exists because job two has an exception: possessive pronouns (its, hers, ours, yours) never take apostrophes. It's is always it is. If you can say it is and the sentence survives, use the apostrophe. If not - the cat licked its paw - no apostrophe, no debate.",
      "That's the whole system. Two jobs, one exception. The apostrophe has been terrifying you with a workload it doesn't have.",
    ],
  },
  {
    slug: "reading-your-way-to-better-english",
    title: "Reading Your Way to Better English",
    dek: "Why readers acquire grammar faster than students learn it.",
    corner: "english",
    topics: ["reading", "learning", "words"],
    contentType: "essay",
    readingDepth: "standard",
    authorName: AUTHORS.june,
    body: [
      "Ask people with beautiful, natural second-language English how they learned, and almost none of them credit grammar tables. They credit books. Comics. Forum threads. Song lyrics badly understood at twelve, correctly understood at twenty.",
      "This is not because reading is a pleasant distraction from real study. It is because reading is real study - the only format in which grammar arrives in its natural habitat, wearing its normal clothes, doing its actual job.",
      "## Grammar as weather",
      "A grammar rule memorized from a table is like a fact about rain: true, but inert. The same rule met a thousand times in stories is weather you have lived in. You stop noticing you know it. Which past tense goes after while? People who have read enough don't check this. They know how the sentence feels.",
      "This is why readers make correct sentences they cannot explain and students explain rules they cannot use. The reader has internalized the pattern at the speed of experience. The student has memorized the pattern at the speed of anxiety.",
      "## The method is embarrassingly simple",
      "Read things you can mostly understand - around 95% - and that you would read in your own language. Fiction is ideal: dialogue teaches speech, narration teaches writing, and stories create memory hooks. When you meet a word you need, check it once. Then keep going.",
      "Do not look up every unknown word. That converts reading into homework, and homework gets quit. Ten enjoyable pages beat ten grueling ones, and the compound interest is startling: at a modest ten pages a day, that's over a million words of English a year - more input than most classrooms deliver in five.",
      "## Vocabulary grows by appointment",
      "Words you meet in a story arrive with a scene attached - the detective's trench coat, the argument at the kitchen table - and scenes are how human memory works. The word serendipity I learned in a novel, attached forever to a character finding a ring in a sofa. I have never needed a flashcard for it since.",
      "Read. It is the slowest-looking, fastest-working method in the entire language-learning world.",
    ],
  },
  {
    slug: "the-last-bus-to-mapusa",
    title: "The Last Bus to Mapusa",
    dek: "A story about a ticket, a promise, and the exact weight of a small town.",
    corner: "story",
    topics: ["short-stories", "fiction", "moments"],
    contentType: "story",
    readingDepth: "quick",
    authorName: AUTHORS.nila,
    body: [
      "The last bus to Mapusa left Panaji at 9:40, and everyone in Goa knew it left at 9:40 except the tourists, who believed timetables.",
      "Ines was not a tourist. She had missed this bus exactly four times in her life, and each time the town had reacted as if she had failed a public exam. The bus stop at 9:35 held its usual parliament: two fisherwomen, a man with a hen, and Mr. D'Souza from the bank, who narrated everything.",
      "\"Nine-thirty-eight,\" said Mr. D'Souza, to no one, to everyone. \"She's making good time today.\"",
      "Ines stood with a ticket in her hand for a girl who was not there yet. Her niece, seventeen, coming in from Pune, changing at Mapusa. Ines had promised her sister, in the way sisters promise - eyes locked, meaning underneath - that she would meet this bus. That she would be standing there. Visible.",
      "The bus arrived at 9:41, because Goa. It emptied: one uncle, one soldier on leave, one backpacker asking a question no one understood. No seventeen-year-old.",
      "The fisherwomen looked at Ines. The man looked at his hen. Mr. D'Souza looked at the sky, the horizon, the whole situation.",
      "\"She's not on it,\" he reported.",
      "\"No,\" said Ines.",
      "\"The Pune bus connects at Pernem. It's late in the monsoon. It's always late in the monsoon.\" He said this with the authority of a man who had missed the connection himself in 1987 and never emotionally recovered. \"The nine-forty will get you to Mapusa by the stand. The Pune bus gets in at half ten. If you take this bus, you'll be there when she arrives. That's what you're doing.\"",
      "Ines looked at her ticket. It was for this bus. It had always been for this bus. But a promise, made to a sister, in the tone her sister had used, is heavier than a ticket, and requires a witness.",
      "\"Yes,\" said Ines. \"That's what I'm doing.\"",
      "The fisherwomen nodded, one each, like a small committee closing a file. The hen man opened his shawl, and the hen looked at Ines with the indifference of a creature who had never once needed to be anywhere for anyone.",
      "The bus to Mapusa - the 9:40, leaving at 9:43 - carried Ines out of Panaji into the green dark of the monsoon, past the same jackfruit tree that had been there for every one of her four failures, and she put her hand on the cold window glass like a girl, though she was fifty-one, because some trips you take for someone else, and everyone at the stop had known it, and everyone had let her.",
    ],
  },
  {
    slug: "what-the-tide-left",
    title: "What the Tide Left",
    dek: "Every morning the sea rearranged the beach. One winter it rearranged her.",
    corner: "story",
    topics: ["real-stories", "personal-essays", "moments"],
    contentType: "story",
    readingDepth: "standard",
    authorName: AUTHORS.amara,
    body: [
      "After the funeral, my grandmother walked the beach every morning at six. This was not grief, she insisted, spelling it out like a foreign word she'd been assigned. It was walking. People did it. There were doctors who recommended it.",
      "We let her have the sentence. The beach was two streets from her house, and the beach is public, and grief is private, so the arrangement worked: her mornings belonged to the sea; her afternoons belonged to us and the uncomfortable silence that sat at the table like an extra relative.",
      "I was fourteen that winter, old enough to be trusted with a task and young enough to be sent on one, which is how I became the tea-carrier. Every morning at seven-fifteen, a flask of tea, two cups - she always packed two - and the walk down to find her.",
      "The second cup was never for me. I never asked who it was for. Forty-one years of marriage had made her a person who packed two cups the way other people are right- or left-handed.",
      "## The beach in winter",
      "A winter beach is an honest place. The sea takes away and takes away, and then every morning, having taken, it leaves an inventory: shells, rope, a shoe, sometimes a whole unbroken glass float from some fishing boat's bad night, extraordinary things, ordinary things.",
      "My grandmother walked the waterline like an inspector. She knew the tide's habits the way you know a difficult relative's - what it would take, what it would return, when it would be calm and when it would be all noise and no apology.",
      "One morning - this is the morning the story is about - there was a dog. Somebody's dog, salt-curled, half-drowned or at least dramatically committed to the role, sitting at the tide line facing the sea with the seriousness of a creature waiting for a ship.",
      "My grandmother stopped. She looked at the dog, and the dog looked at the sea, and then, without a word, she poured the second cup of tea onto the sand in front of it.",
      "Dogs, obviously, do not drink tea. This was not a rational act. But the dog turned around - away from the sea, toward the pouring, toward the smell of cardamom and the human holding the cup - and that was the whole miracle, that turning. It walked home with us. We named it Tea.",
      "## After",
      "I am older now than she was that winter, and I understand what I couldn't at fourteen: she wasn't walking off her grief. She was walking with it - out to the edge of the house, twice a day, at hours when nobody could see her talk to the sea. And when the sea finally answered - in the shape of a bedraggled dog that needed her, that turned from the water when she called - the second cup finally had somewhere to go.",
      "The sea takes and takes. Everyone says this at funerals. What they say less is that every single morning, it also gives back: shells, rope, glass floats, and one winter, for a woman carrying two cups down a public beach - something to carry them both for.",
    ],
  },
  {
    slug: "the-interview-that-wasnt",
    title: "The Interview That Wasn't",
    dek: "He prepared three weeks for questions no one asked.",
    corner: "story",
    topics: ["real-stories", "character-life", "moments"],
    contentType: "story",
    readingDepth: "quick",
    authorName: AUTHORS.marcus,
    body: [
      "Vikram prepared for the interview the way other men prepare for marathons. Three weeks. Seventy interview questions typed, printed, taped to the fridge. He rehearsed his weaknesses until they sounded like strengths in witness protection. Where do you see yourself in five years - he had charts.",
      "The building was glass, the kind that reflects you back at yourself at a slightly better angle. The receptionist offered water. He took it, because his mouth was a desert, and then held the cup like a small embarrassing prop for forty minutes because there was nowhere to put it down.",
      "The interviewer, Ms. Okafor, arrived at speed, coffee in hand, ten minutes late and profoundly uninterested in apologizing for it. She read his CV for the first time, vertically, like a menu she'd already studied in a previous life.",
      "\"Okay,\" she said. \"You're the one who worked at the bookshop.\"",
      "\"That was part-time, during-\"",
      "\"My son loves that shop. The little one. He saves money for weeks and comes in with the exact amount, and your staff are - I've watched them - they let him count it out. Every coin. Nobody rushes him.\" She looked up. \"Why?\"",
      "Vikram opened his mouth to say something about customer experience frameworks. What came out, because he had held a water cup for forty minutes and any rehearsal left in him had evaporated, was: \"Because he's saving up for something he really wants. Everyone in the shop knows what that's like. It's basically the whole reason anyone works in a bookshop - you get to be near people doing that.\"",
      "Ms. Okafor looked at him for a moment, wrote one word on the CV, and stood up.",
      "The seventy questions never came up. He was offered the job on Monday. He never learned the word she wrote on the CV. He suspects, and has suspected for nine years, that it was just: bookshop.",
    ],
  },
  {
    slug: "the-speed-of-modern-attention",
    title: "The Speed of Modern Attention",
    dek: "We optimized information for delivery and accidentally optimized people for impatience.",
    corner: "thought",
    topics: ["culture", "ideas", "perspective"],
    contentType: "essay",
    readingDepth: "deep",
    authorName: AUTHORS.thea,
    body: [
      "There is a number worth knowing: it took radio thirty-eight years to reach fifty million people. Television: thirteen. The internet: four. A certain smartphone game involving birds: thirty-five days. We tell this story as a story of progress, and it is. But progress has a shadow variable, and the variable is us.",
      "Every delivery system ever built has two ends: the information enters at one end, and a nervous system receives it at the other. We have spent fifty years making extraordinary investments at the first end - compression, bandwidth, algorithms - and roughly none at the second. The receiving end, the human attention span, is legacy hardware running software it was never designed for.",
      "## What optimization actually does",
      "When an industry optimizes for engagement, it is optimizing for the shortest loop between stimulus and response. The shorter the loop, the more loops per minute; the more loops, the more revenue. This is not a conspiracy - nobody in a meeting says let's shrink attention - it is simply what the metric selects for.",
      "And what the metric selects, it breeds. Content gets punchier. Articles get shorter, then they become videos, then thirty-second videos, then fifteen, then a feed that is nothing but an endless hallway of half-second doors.",
      "## The cost is not stupidity",
      "The common fear - screens are making us dumb - is too simple. The deeper cost is what economists would call a switching cost: we are losing the ability to pay the entry toll of depth. Deep work, real reading, friendship itself - all are front-loaded. They demand a slow ramp before the payoff, and we are becoming people who can't afford the ramp.",
      "It is not that we cannot understand long things. It is that we now flinch before the ramp starts. The flinch is the change.",
      "## The counter-move",
      "What to do? The honest answer is not digital detox theater - a week off does nothing except remind you how loud it is. The counter-move is to become a deliberately slow receiver. To practice things whose value cannot be compressed: a craft with your hands, a long book, a conversation with no phone on the table.",
      "Depth has a compounding return that shallowness mathematically cannot offer: a shallow hour costs an hour. A deep hour buys a slightly deeper you, and the depth carries forward.",
      "The age is not ending. The bandwidth will only grow. But attention - real, sustained, un-monetized attention - is quietly becoming a rare resource. And rare resources have a future.",
    ],
  },
  {
    slug: "in-defense-of-boring-questions",
    title: "In Defense of Boring Questions",
    dek: "The questions everyone is sick of are usually the ones doing the real work.",
    corner: "thought",
    topics: ["questions", "philosophy", "perspective"],
    contentType: "opinion",
    readingDepth: "standard",
    authorName: AUTHORS.marcus,
    body: [
      "Every field has its despised questions. In philosophy it's the classics - what is meaning, what is a person, what makes a life good - mocked by the ambitious as undergraduate material. In conversation, the crime is even more specific: the boring question. How are you. What do you do. Where are you from. The online world has built a whole genre about how to ask better, more interesting questions instead.",
      "I want to argue, quietly and against the mood, for the boring question.",
      "## Boring questions are load-bearing",
      "Nobody finds What do you do? interesting because nobody has ever answered it. That is the point. The boring question isn't a question; it's a door. Its content is not in the words - its content is the two seconds of willingness it takes to answer. The interesting question, asked of a stranger, demands something before trust exists. The boring question builds the trust. You cannot get to the interesting question without paying the toll of several boring ones.",
      "This is why small talk is a technology, not a failure of imagination. Weather is the safest shared reality two strangers own. Talking about it is a handshake that says: we are both here, we both noticed the world, we may now proceed.",
      "## The boring classics",
      "The deep questions - free will, meaning, what makes a life good - are despised by sophisticated people in the exact way that warm-up exercises are despised by people who want to be athletes. What if my life is good but not meaningful? is mocked as a freshman question right up until 3 a.m. some specific night when it is suddenly, catastrophically, the only question.",
      "Fields despise their boring questions when the questions get hard. Philosophy's crime is not that it asks them but that it has been asking for 2,400 years and people expect progress - as if these were engineering problems and not, perhaps, the permanent maintenance schedule of being human.",
      "## Practice",
      "Ask the boring question with actual attention this week. How are you - and then hear the answer; wait the extra beat where the real answer lives. What do you do - asked of the person at the bus stop, not the networking event, changes the entire species of the question.",
      "The boring questions are where everyone is. That is why they matter. Interesting is an address; boring is a street, and everything is on it.",
    ],
  },
  {
    slug: "on-being-easily-replaced",
    title: "On Being Easily Replaced",
    dek: "A calmer way to think about job security in an automated age.",
    corner: "thought",
    topics: ["ideas", "culture", "opinions"],
    contentType: "essay",
    readingDepth: "standard",
    authorName: AUTHORS.june,
    body: [
      "There is a new anxiety in town, and it is very polite about itself. It doesn't say you will lose your job. It says tasks, not jobs, will be automated - and then it pauses, in a way that lets you do the arithmetic alone.",
      "The standard response to this anxiety is a kind of frantic self-marketing: become irreplaceable. Build a personal brand. Learn seven tools before Thursday. But I want to suggest that irreplaceability is a stressful, losing game - and that there is a calmer one.",
      "## Nobody is irreplaceable. Teams are.",
      "Here is a strange thing that anyone who has managed people eventually learns: the irreplaceable person is a liability. They become the bottleneck, the single point of failure, the reason decisions wait. Every competent organization's actual goal is to have no irreplaceable people - which means chasing irreplaceability is chasing a position organizations are actively working to eliminate.",
      "What organizations actually protect, in every restructuring I have ever watched, is not the brilliant lone genius. It is the connective tissue: people who make everyone around them 10% better, who know where everything is, who are trusted at the exact points where trust is expensive to rebuild.",
      "## The three protections",
      "Being easy to work with is a moat. It is unglamorous and nearly impossible to automate. Careful institutional memory - knowing why the decision was made, not just what it was - is a moat. And being the person whose word is reliable - a flinch-free yes, a clean no - is a moat. None of these are skills in the certificate sense. All of them are scarce, and scarcity is the entire economy of security.",
      "## The humble math",
      "The game, then, is not irreplaceable but hard-to-replace-well. The first is a fortress, and fortresses are expensive and lonely. The second is a garden: it takes regular, modest work, it makes the whole neighborhood nicer, and - the entire point - it survives the owner taking a vacation.",
      "Automate away. The connective tissue of a workplace is the last thing on the list, and the last people standing are almost never the ones who hoarded their value. They are the ones who gave it away in every direction, and became, quietly, the reason the place still worked.",
    ],
  },
  {
    slug: "how-to-make-a-big-decision",
    title: "How to Make a Big Decision When You Feel Frozen",
    dek: "A practical guide: three techniques that work when pros-and-cons lists don't.",
    corner: "help",
    topics: ["decisions", "how-to", "practical-guides"],
    contentType: "guide",
    readingDepth: "standard",
    authorName: AUTHORS.dev,
    body: [
      "Big decisions are hard for a boring reason: they are irreversible-ish. Should I take the job, move cities, leave the field - each asks you to pick a future while standing in the present, where all futures are equally hypothetical. The pros-and-cons list fails because it assumes the difficulty is informational. It isn't. You have the information. You lack a decision procedure.",
      "This is a guide to three procedures that work.",
      "## Technique one: the ten-ten-ten",
      "For any option, ask: how will I feel about this in ten minutes? Ten months? Ten years? The technique's power is that it separates the two voices that get tangled in big decisions: the fear of discomfort now, and the regret of loss later.",
      "Ten minutes after quitting: awful, sweating, drafting a retraction. Ten months: probably settled, either way. Ten years: nobody remembers the fear; everyone lives with the outcome. Most bad decisions are made by letting the ten-minute voice vote three times. Ten-ten-ten gives the long voices one fair turn.",
      "## Technique two: the coin flip (yes, really)",
      "Assign the two options to a coin, flip it - and then, while it's in the air, notice which side you're hoping for. The technique is not the coin. The coin is a machine for surfacing a preference you already hold but have been refusing to hear. You don't have to obey the coin. You just had your answer; the flip is how you caught it.",
      "If the coin lands and you feel nothing - genuinely nothing - that's data too: the choice is smaller than it feels, and you can flip an actual coin and get on with your life.",
      "## Technique three: make the decision small",
      "Frozen decisions are usually over-sized. You cannot decide should I move to Lisbon - it's too heavy to lift in one go. So split it: book a two-week trip instead. Test the job - freelance for one client on weekends. Every big decision contains a small reversible pilot, and pilots convert terror into data.",
      "The pilot rule also quietly answers the classic fear - what if I make the wrong choice? - because pilots are nearly un-wrongable. A two-week trial teaches you more than six months of deliberation, at none of the cost.",
      "## The last thing",
      "After you decide, stop re-deciding. Most post-decision misery is not the outcome of the choice but the habit of auditing it nightly, holding the ghost of the other option up against your real life. Set a review date - six months out - and until then, the decision is closed. This is a skill, and it is learnable, and it is the entire difference between deciders and worriers: deciders are not better at choosing. They are better at stopping.",
    ],
  },
  {
    slug: "how-to-say-no",
    title: "How to Say No Without a Paragraph",
    dek: "The practical art of the clean, kind, complete refusal.",
    corner: "help",
    topics: ["how-to", "communication", "everyday-problems"],
    contentType: "guide",
    readingDepth: "quick",
    authorName: AUTHORS.june,
    body: [
      "Most of us are bad at saying no because we believe a no requires a case: an apology, a reason, a counteroffer, and preferably a small tragic story about how impossibly full the week is. So we say yes at the moment of highest social pressure and resent it at leisure.",
      "Here is the entire guide, compressed: a good no is short, kind, and complete. You need all three, and you need nothing else.",
      "## Short",
      "\"I can't make it - thanks for thinking of me.\" That's a complete no. Notice what it doesn't include: the reason. Reasons are where it goes wrong, because every reason is negotiable. Oh, you're busy that night? What about the next? A no with a reason is an invitation to solve the obstacle.",
      "## Kind",
      "Short without kindness reads as cold, and cold nos start conflicts that short nos were meant to avoid. The kindness belongs in the framing, not the excuse: thanks for asking me, I appreciate it, I hope it's a great one. Warmth is the delivery. The refusal is the content. Do not confuse the two channels.",
      "## Complete",
      "The most common mistake is the no that isn't - maybe, let me see, I'll try to make it work, probably not but I'll let you know. This isn't kindness; it's a deferred no with interest. The person on the receiving end now has to ask again, which is worse for both of you. If the answer is no, deliver it once.",
      "## Practice sentence",
      "Thanks so much for asking - I can't make it. Have a great one. Fourteen words. Every future no you have to give is easier than this one, and this one is already fine.",
    ],
  },
  {
    slug: "fixing-your-sleep-in-a-week",
    title: "Fixing Your Sleep in One Week (the Unexciting Method)",
    dek: "No supplements. One schedule. The seven-day reset.",
    corner: "help",
    topics: ["how-to", "habits", "practical-guides"],
    contentType: "guide",
    readingDepth: "standard",
    authorName: AUTHORS.nila,
    body: [
      "Sleep advice comes in two flavors: sleep-hygiene theater (lavender, sock-wearing, an entire religion of the bedroom) and pharmacology. What actually fixes most broken sleep is neither. It is one boring intervention - a fixed wake time - applied for seven consecutive days.",
      "Here is the week.",
      "## Day one: pick your real wake time",
      "Not your aspirational one. Your realistic one, seven days a week, including weekends. If you currently get up at 9 on Saturday and 6 on Monday, your body is doing a weekly jet lag, and no amount of lavender will help.",
      "The fixed wake time matters because the wake time anchors the whole rhythm. Bedtime is a suggestion; the body sets its sleep pressure off when you got up. Anchor the morning and the evening largely solves itself.",
      "## Days one to three: get up at the time, whatever happened before it",
      "The first three days are the sacrifice. You may have slept badly; you get up anyway. This is the part people resist, and it is the mechanism: sleep pressure is a debt. A short night makes the next night's debt deeper, and sleep arrives sooner, heavier. You are not white-knuckling your way to health - you are building an appetite.",
      "No naps. A nap is a withdrawal from the account you are trying to fill.",
      "## Days four to six: let bedtime float",
      "Do not set a bedtime yet. Go to bed only when actually sleepy - heavy eyelids, not just bored. If you lie down and your mind is a browser with forty tabs, get up, dim lights, read something paper, return when sleepy. Lying awake in bed teaches your body that bed is a worrying-place. Getting up briefly un-teaches it.",
      "## Day seven: audit and adjust",
      "After a week, most people find bedtime has floated earlier on its own and stabilized. Now you can set a wind-down thirty minutes before it: lights lower, phone in another room - not for purity reasons, but because the screen is a small sun, and you are trying to convince a very old system that it is night.",
      "## The honest footnote",
      "If a fixed wake time plus daylight in the morning doesn't shift things after two honest weeks, see a doctor - persistent sleep trouble is a symptom with a real differential, and you deserve an actual diagnosis, not a better pillow.",
    ],
  },
];

export const READING_PATH = {
  slug: "feeling-stuck",
  title: "Feeling Stuck",
  description:
    "Five pieces on the gap between wanting change and knowing what to change.",
  steps: [
    "feeling-stuck-going-nowhere",
    "pressure-to-have-a-direction",
    "why-change-sometimes-looks-like-nothing",
    "learning-to-make-smaller-decisions",
    "building-a-life-you-recognize",
  ],
};

export const VOCABULARY = [
  {
    word: "serendipity",
    sourceArticleSlug: "reading-your-way-to-better-english",
    pronunciation: "seh-run-DIP-ih-tee",
    partOfSpeech: "noun",
    plainMeaning:
      "the luck of finding something good while you were looking for something else",
    usageExample:
      "I went out for bread and came home with a best friend - pure serendipity.",
    etymology:
      "From the Persian tale of the Three Princes of Serendip, who made discoveries by accident - and had the wisdom to notice them.",
    commonMistakes:
      "Often confused with luck; serendipity specifically means a happy accident while seeking something else.",
    relatedWords: ["fluke", "happenstance", "windfall"],
    conversationExamples: [
      "It was complete serendipity - the book was lying on the seat next to mine.",
    ],
  },
  {
    word: "petrichor",
    sourceArticleSlug: "words-that-dont-translate",
    pronunciation: "PET-ri-kor",
    partOfSpeech: "noun",
    plainMeaning: "the smell of rain on dry earth",
    usageExample:
      "The first drops hit the dust and the whole street filled with petrichor.",
    etymology:
      "Coined in 1964 by Australian scientists, from Greek petra (stone) + ichor (the fluid in gods' veins).",
    relatedWords: ["after-rain smell", "geosmin"],
    conversationExamples: [
      "Open the window - you can smell the petrichor.",
      "Petrichor is the single best argument for monsoon season.",
    ],
  },
  {
    word: "sonder",
    sourceArticleSlug: "what-the-tide-left",
    pronunciation: "SON-der",
    partOfSpeech: "noun",
    plainMeaning:
      "the realization that every passerby has a life as full and complex as your own",
    usageExample:
      "Watching the train crowd, a wave of sonder hit her - every face, a whole universe.",
    etymology: "A modern coinage from the Dictionary of Obscure Sorrows.",
    relatedWords: ["empathy", "perspective"],
    conversationExamples: [
      "I had a moment of sonder in the airport - all these people with mothers and Thursdays.",
    ],
  },
  {
    word: "apricity",
    sourceArticleSlug: "words-that-dont-translate",
    pronunciation: "a-PRISS-ih-tee",
    partOfSpeech: "noun",
    plainMeaning: "the warmth of the sun in winter",
    usageExample:
      "There is a word for this - apricity - the sun's kindness in the coldest months.",
    etymology: "From Latin apricus, warmed by the sun. Rare, but real.",
    commonMistakes: "Not related to apricot - the resemblance is a coincidence.",
    relatedWords: ["winter sun", "warmth"],
    conversationExamples: [
      "Stand here a minute - pure apricity.",
    ],
  },
  {
    word: "perfunctory",
    sourceArticleSlug: "the-speed-of-modern-attention",
    pronunciation: "per-FUNK-tuh-ree",
    partOfSpeech: "adjective",
    plainMeaning:
      "done without real care or interest, as a routine or duty",
    usageExample:
      "He gave a perfunctory nod and went back to his phone.",
    etymology: "From Latin perfungi, to get through with, to be done with.",
    commonMistakes:
      "Does not mean rude - a perfunctory greeting is quick and careless, not hostile.",
    relatedWords: ["cursory", "offhand", "mechanical"],
    conversationExamples: [
      "A perfunctory 'how are you' does not expect an answer.",
      "The review felt perfunctory - two sentences and a star.",
    ],
  },
  {
    word: "salience",
    sourceArticleSlug: "how-people-actually-change",
    pronunciation: "SAY-lee-ence",
    partOfSpeech: "noun",
    plainMeaning:
      "the quality of standing out and demanding attention",
    usageExample:
      "The salience of a habit cue matters more than the strength of your willpower.",
    etymology: "From Latin salire, to leap. What salient does - leaps at you.",
    commonMistakes: "Salient points leap out; they are not merely important.",
    relatedWords: ["prominence", "noticeability"],
    conversationExamples: [
      "Make the cue salient - put the guitar where the couch used to be.",
    ],
  },
];

/** Tiptap-compatible JSON doc built from plain paragraphs + ## headings. */
export function bodyToTiptapDoc(body: string[]) {
  const content: Array<Record<string, unknown>> = [];
  for (const para of body) {
    if (para.startsWith("## ")) {
      content.push({ type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: para.slice(3) }] });
    } else if (para.startsWith("# ")) {
      content.push({ type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: para.slice(2) }] });
    } else {
      content.push({ type: "paragraph", content: [{ type: "text", text: para }] });
    }
  }
  return { type: "doc", content };
}

export function bodyToPlainText(body: string[]) {
  return body.join("\n\n");
}
